### ISSUE TITLE
missing validation of input for volume specification of machine

### ISSUE THREAD

**Issue by lukas016** [ironcore-dev/libvirt-provider#131]
**Describe the bug**
currently it is possible send over iri command create machine with invalid specification of volume. I observed 2 wrong cases which are possible:

1. Create VM with the same name of disk:

    ```yaml
   volumes:
   - empty_disk:
        size_bytes: 5368709120
      name: ephe-disk
      device: odb
    - empty_disk:
        size_bytes: 5368709120
      name: ephe-disk
      device: odd
    - empty_disk:
        size_bytes: 530000000
      name: ephe-disk2
      device: odc
    ```

    This specification contains 2 different disk with the same name. Problem is: it will create VM with only last specified disk with the same name. So we created vm with different as requested specification. I requested 3 disk and i got 2.

2. I can define multiple time the same device

    In this case object is created in store, but VM isn't created because the same device can be use only one time in libvirt. Of course, it isn't big issue, but it will affect other logic as GC, healtchecker, ... which run independently and they always iterate over all machines in store.

**To Reproduce**
1. Create machine
    1. Create machine with volume specification where you have 2 this with the same name and different device
    2. Create machine with volume specification where you have 2 disk with the same device
3. Watch logs
4. Check domain xml of vm (1.i)

**Expected behavior**

Discussion:
- better validation process
- other component will solve issue
